### ISSUE TITLE
Remove Application Profiles

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/draft-ietf-cbor-cde#14]
Application Profiles seem like an unnecessary complexity to me in an area that (I think) we're trying to make simpler.

I look at this draft as a really useful rewording of some important stuff in section 4 and 5 of RFC 8949. Those sections of 8949 are a bit complicated for readers, so this draft should be simple.

So far the only proposed profile is dCBOR. I think dCBOR exists just fine without the notion of application profiles, just like CDE exists just fine on top of preferred serialization.

To justify the complexity application profiles add, I think we'd want to have three solid use cases for them.

Application profiles are only for variations of CDE. They are not for variations of preferred serialization or a general profile mechanism for all of CBOR. This makes them much much less useful.

**Comment by cabo** [comment]
Can you explain how giving the concept a name adds complexity?

**Comment by laurencelundblade** [comment]
Doesn't the burden of justification for something in a document lie with the proponent of the something?

A short answer to your question is that for us careful implementors every concept in a document must be read, digested, thought through and understood to be sure of correctness and completeness.

But, I don't think things should go in documents unless there is justification.

**Comment by cabo** [comment]
Of course.  The most recent mail where I tried to explain the reason for them is Archived-At: <https://mailarchive.ietf.org/arch/msg/cbor/7CAgHZxvj34Rf4rcXFGeFwBzv_M>

To make a decision, it is necessary not only to understand the benefit, but also the cost of the feature.
To me it seems it creates zero cost for those who do not implement it.
If you think you do not need it, I would not implement it.

**Comment by laurencelundblade** [comment]
I don't see how the cost is zero. You have to understand it to know that you don't have to implement it.

There's a cost to protocol designers too. They have to understand it to know whether they should use it or not use it.

There's also some cost to the WG, the IESG and the RFC editor to review.

**Comment by cabo** [comment]
We could improve the text to make this easier to understand.

The cost of *not* having the feature is immense.
People will notice that their application data model does not map cleanly to CDE and will do exactly what dCBOR did in the outset -- reinvent a incompatible variant of CDE.
So it is absolutely worth massive effort to have application profiles as a concept in place.
I still believe the actual effort is minimal, and I would like to understand what text in CDE creates complexity for you, and how we could minimize the discovery cost for those whose actual cost is zero because they don't need it.

**Comment by cabo** [comment]
PR #15 should address most of your concerns, without removing the concept of Application Profiles entirely.

**Comment by laurencelundblade** [comment]
While moving to an appendix is an improvement, I still would like to see application profiles removed. I was waiting for the meeting on Friday before completing the review.

**Comment by cyberphone** [comment]
1. Currently CBOR support (=profiles) is _implicitly_ or _explicitly_ specified as a part of applications and implementations. Deterministic encoding does IMO not motivate a change.

2. Referencing dCBOR indirectly transcends Numeric Reduction into an "IETF-standardized" encoding method, although dCBOR was rejected as a WG item.  The dCBOR spec. can refer to CBOR-CDE without the application profile concept in the same way as CBOR-CDE refers to RFC 8949.
