### ISSUE TITLE
terminology: f16, float16, binary16

### ISSUE THREAD

**Issue by cabo** [cbor-wg/draft-ietf-cbor-cde#3]
Do not mix up these terms:

* f16 (Rust name for a platform level storage type),
* float16 (CDDL name for a floating point precision and range), and 
* binary16 (IEEE 754 name for a binary representation of floating point values).

(and 32, 64).

**Comment by hildjj** [comment]
Is this issue overcome by events?

**Comment by cabo** [comment]
CDE currently doesn't mention these different concepts.
The explainer does, but I don't find any place that needs immediate attention.
(Obviously, we want to keep the principle in mind.)
