### ISSUE TITLE
additional information in integers vs doubles

### ISSUE THREAD

**Issue by dwaite** [cbor-wg/draft-ietf-cbor-cde#4]
In the section on reducing floating point numbers to integers, I believe it would be appropriate to clearly specify behavior of other floating point reductions, e.g. reducing 0.5 from double to a half-width float.

In addition, I believe the behavior needs to be defined as to what an application should do when conversion of an integer to a floating point number is in itself lossy, e.g. what to do if an application expects a double but the CBOR value received is the decimal 9007199254740993. Silent truncation would make the round-trip non-deterministic.

**Comment by hildjj** [comment]
See the section on [preferred serialization](https://www.rfc-editor.org/rfc/rfc8949.html#name-preferred-serialization) in RFC8949, and read the dCBOR [draft](https://www.ietf.org/archive/id/draft-mcnally-deterministic-cbor-07.html), then see what else this spec needs?

**Comment by cabo** [comment]
Additional information about the use of numbers in CBOR has been captured in https://www.ietf.org/archive/id/draft-bormann-cbor-numbers-00.html -- I believe if we need any additional discussion of this, that should go there.
